Task 1 completed
BathSpaWebDev/JustHere4Popcorn pull request #2
Opened 2022-01-12 12:16 UTC by kely-rufino

### Display the film collection

Display a list to browse with each film title, the year it was made, the price, whether it's in stock, and each of its genres

2022-01-13 10:22 UTC, luciavelasco commented on README.md
> -Secondhand Movies
Did you mean to remove this?

2022-01-13 10:24 UTC, luciavelasco commented on src/App.js
> +import AllMeetupsPage from './pages/AllMeetups';
Why is this called "Meetups"? This should be DVDs

2022-01-13 10:24 UTC, luciavelasco commented on src/App.js
> +          <Route path='/' element={<AllMeetupsPage/>}></Route>
Are you planning on adding more routes to this app?

2022-01-13 10:34 UTC, luciavelasco commented on src/components/meetups/MeetupItem.module.css
> +
Why is this file called `*.module.css`?

2022-01-13 10:35 UTC, luciavelasco commented on src/components/meetups/MeetupItem.module.css
> +    padding: 0.5rem 1.5rem;
I like that you're using rem here, I think it's a bit more reliable than pixels.

2022-01-13 10:35 UTC, luciavelasco commented on src/components/meetups/MeetupList.js
> +function MeetupList(props){
Rename this

2022-01-13 10:35 UTC, luciavelasco commented on src/components/meetups/MeetupList.js
> +        <ul className={classes.list}>
What does this do?

2022-01-13 10:36 UTC, luciavelasco commented on src/components/meetups/MeetupList.js
> +                key={meetup.id}
Really good use of id as a key!!!

2022-01-13 10:36 UTC, luciavelasco commented on src/components/meetups/MeetupList.module.css
> +
Remove this empty line

2022-01-13 10:37 UTC, luciavelasco commented on src/components/meetups/MeetupList.module.css
> +
remove empty lines in css file

2022-01-13 10:37 UTC, luciavelasco commented on src/components/meetups/MeetupList.module.css
> +
remove this empty line

2022-01-13 10:38 UTC, luciavelasco commented on src/components/meetups/Meetupitem.js
> +    <div className={classes.display}>
How does this work if you want to add multiple classes to one element?

2022-01-13 10:39 UTC, luciavelasco commented on src/components/meetups/Meetupitem.js
> +        <div className={classes.image}>
children of a component should be indented, please fix it to be more like:

```jsx
<Card>
    <div></div>
</Card>
```

not 

```jsx
<Card>
<div></div>
</Card>
```

2022-01-13 10:40 UTC, luciavelasco commented on src/components/meetups/Meetupitem.js
> +            <p>{props.genre}</p>
Each genre should be listed separately

2022-01-13 10:41 UTC, luciavelasco commented on src/components/meetups/Meetupitem.js
> +            <button>Add to Cart</button>
Remove this button, as there is no cart until Task 2

2022-01-13 10:42 UTC, luciavelasco commented on src/components/ui/Card.js
> +function Card(props) {
I'm not sure if this needs to be its own element, however I like the use of `children` and you don't need to change this (just something to bear in mind next time).

2022-01-13 10:43 UTC, luciavelasco commented on src/index.css
> +
empty line, pls remove

2022-01-13 10:44 UTC, luciavelasco commented on src/index.css
> +.btn {
I prefer using long/full words for class names, i.e. `button` not `btn`.
Optional

2022-01-13 10:45 UTC, luciavelasco commented on src/index.css
> +.btn--alt {
Interesting double-hyphen convention:
`btn--alt`
`btn-alt`
Make sure the team is on the same page about this.

2022-01-13 10:46 UTC, luciavelasco commented on src/index.css
> +.modal {
Is this being used anywhere? If not, please remove this class.

2022-01-13 10:46 UTC, luciavelasco commented on src/index.css
> +.modal {
If you aren't using it now, but are GOING to use it, you can keep it.

2022-01-13 10:47 UTC, luciavelasco commented on src/index.css
> +.backdrop {
same as above, is this being used?

2022-01-13 10:48 UTC, luciavelasco commented on src/pages/AllMeetups.js
> +        fetch ("DVDdata.json")
Fix the spacing:
`fetch("DVDdata.json")`
not
`fetch ("DVDdata.json")`

2022-01-13 10:49 UTC, luciavelasco commented on src/pages/AllMeetups.js
> +  const [loadedMeetups, setLoaderMeetups] = useState([]);
either rename this to dvds, or have a loading state. Optional

2022-01-13 10:51 UTC, luciavelasco requested changes
Please rename the word Meetups to Dvds everywhere (use Cmd+Shift+R for easy renaming).

And please use better commit messages, for example:
"Create React App and copy over template"
"Add DVD data to page"
"Fix bug"

2022-01-13 14:28 UTC, JoeLam930 commented
Renamed "meetupItem" to "DVDsItem"
Renamed "meetuplist" to "DVDslist"
Renamed "Allmeetup" to "AllDVDs"
Renamed "meetups" folder to "DVDsItemsandlists"

2022-01-14 10:17 UTC, kely-rufino commented
The PR it's not finished, we need review.

2022-01-14 10:26 UTC, luciavelasco commented on package.json
> +    "create-react-app": "^5.0.0",
I don't think you need this

2022-01-14 10:34 UTC, luciavelasco commented on src/components/DVDsItemsandlists/DVDsItem.js
> +            <p>{props.genre}</p>
The genres need to be listed separately

2022-01-14 10:35 UTC, luciavelasco commented on src/components/DVDsItemsandlists/DVDsItem.js
> +    <li>
This shouldn't be a list item, and it should not be in an unordered list, as it is only a single item

2022-01-14 10:38 UTC, luciavelasco commented on src/components/DVDsItemsandlists/DVDsItem.css
> +  li {
you probably shouldn't have changed this, i think there was a mixup about the genre vs the whole film

2022-01-14 10:38 UTC, luciavelasco requested changes
I think three more comments - nearly there, it looks good!!

2022-01-14 11:28 UTC, luciavelasco commented on src/components/DVDsItemsandlists/DVDsItem.css
> +  li {
I have no idea how to fix this. When I change it to a class name it doesn't work.

2022-01-14 11:32 UTC, luciavelasco commented on src/components/DVDsItemsandlists/DVDsItem.css
> +  li {
Fixed it, the ul was being used in a different file without being imported directly.

2022-01-14 11:36 UTC, luciavelasco approved these changes
This looks resolved now, I'm happy for this to be merged with main 🎉

2022-01-14 11:41 UTC, merged